optimization of the adjustNumber function
objectionary/eo2js pull request #107
Opened 2024-10-25 19:47 UTC by Akvadevka

I refactored adjustNumber to enhance readability and simplify the logic, reducing the number of checks and iterations over the array.

2024-10-28 00:08 UTC, yegor256 commented
@maxonfjvipon please, review this one

2024-10-28 07:39 UTC, maxonfjvipon commented
@Akvadevka what ticket your pull request is connected to? What problem did you try to solve?

2024-10-28 18:42 UTC, Akvadevka commented
@maxonfjvipon no ticket. I wrote my purposes in the description.

2024-10-30 14:29 UTC, maxonfjvipon requested changes

2024-10-30 14:29 UTC, maxonfjvipon commented on eo2js-runtime/src/runtime/bytes-of.js
> +          `Wrong format of element ${hex} in byte array ${bytes}\nShould be either integer of hexadecimal starting with '0x'`
@Akvadevka there's something wrong with indentation

2024-10-30 14:29 UTC, maxonfjvipon commented on eo2js-runtime/src/runtime/bytes-of.js
> +  if (bytes.length !== 8) return bytes;
@Akvadevka we're trying to avoid many `return` statements, [here's](https://www.yegor256.com/2015/08/18/multiple-return-statements-in-oop.html) why

2024-10-30 14:29 UTC, maxonfjvipon commented on eo2js-runtime/src/runtime/bytes-of.js
> +      Math.abs(byte - number[index]) === 256 ? byte - 256 : byte
@Akvadevka I don't see the purpose of the change. Replacing `if` with ternary operator didn't make the code more readable

2025-11-17 11:37 UTC, maxonfjvipon commented
@Akvadevka I'm closing this one since there's no activity for a long time

2025-11-17 11:37 UTC, closed without merging