Feat/add proper logging
objectionary/eo2js pull request #116
Opened 2024-11-06 18:46 UTC by HaidarJbeily7

related to this [Issue](https://github.com/objectionary/eo2js/issues/85)

2024-11-08 18:26 UTC, maxonfjvipon requested changes

2024-11-08 18:26 UTC, maxonfjvipon commented on eo2js/src/commands/dataize.js
> +  console.log(`Using main file: ${main}`)
@HaidarJbeily7 let's merge these two `console.log`s into single one

2024-11-08 18:26 UTC, maxonfjvipon commented on eo2js/src/commands/link.js
> +  console.log('Creating package.json...')
@HaidarJbeily7 let's move this log to 3 lines below and print something like: `created package.json in ...` where ... is path

2024-11-08 18:26 UTC, maxonfjvipon commented on eo2js/src/commands/link.js
> +  console.log(`Copying ${main} file...`)
@HaidarJbeily7 let's move this log below after copying is done and print something like: `copied file to directory`

2024-11-08 18:26 UTC, maxonfjvipon commented on eo2js/src/commands/link.js
> +    console.log(`Copying local eo2js-runtime from: ${options.dependency}`)
@HaidarJbeily7 same as above

2024-11-09 13:31 UTC, HaidarJbeily7 commented
Closes: #85

2024-11-09 13:41 UTC, maxonfjvipon approved these changes
@HaidarJbeily7 LGTM

2024-11-09 13:42 UTC, maxonfjvipon commented
@rultor merge

2024-11-09 13:45 UTC, rultor commented
> @rultor merge

@maxonfjvipon OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/45078-2466221333).

2024-11-09 14:08 UTC, merged

2024-11-09 14:08 UTC, rultor commented
> @rultor merge

@maxonfjvipon Done! FYI, the full log is [here](https://www.rultor.com/t/45078-2466221333) (took me 22min).

2024-11-10 05:34 UTC, maxonfjvipon commented
@HaidarJbeily7 thanks