Improve error handling in transpile command
objectionary/eo2js pull request #124
Opened 2024-12-16 14:29 UTC by 2IMT

- Catch all other errors in transform() function and report them to the user
- Improve error messages for non-existent or invalid foreign files

2024-12-17 06:47 UTC, 2IMT commented
@maxonfjvipon, could you please review?

2024-12-18 09:38 UTC, yegor256 commented
@maxonfjvipon please, take a look

2024-12-20 13:56 UTC, maxonfjvipon requested changes

2024-12-20 13:56 UTC, maxonfjvipon commented on eo2js/src/commands/transpile.js
> +    return;
@2IMT we're trying to avoid multiple return statements, here's why: https://www.yegor256.com/2015/08/18/multiple-return-statements-in-oop.html

2024-12-20 13:56 UTC, maxonfjvipon commented on eo2js/src/commands/transpile.js
> +    throw new Error(`Invalid foreign tojo file format: ${foreign.substring(foreign.lastIndexOf(path.sep))}. Only .json files are supported.`);
@2IMT I don't understand the purpose of the change

2024-12-20 13:56 UTC, maxonfjvipon commented on eo2js/src/commands/transpile.js
> +    throw new Error(`File not found: ${foreign}. Ensure the file exists and is accessible.`)
@2IMT I don't understand the purpose of the change

2024-12-26 07:03 UTC, 0crat commented
@2IMT It is [not a good idea](https://www.yegor256.com/2014/04/15/github-guidelines.html) to name Git branches the way you named this one: "`master`". You've earned -12 points. Next time, better give your branch the same name as the number of the ticket that you are solving. In this case, a perfect name, for example, would be "`123`".

2025-10-19 07:30 UTC, closed without merging